### ISSUE TITLE
[META] Auflistungen aller benötigten Inhalte

### ISSUE THREAD

**Issue by mootari** [drupal-usergroup-berlin/dug-website#25]
- [x] Intro: Startseite (#11)
- [x] Intro: Seite Events (-)
- [x] Intro: Seite Talks (-)
- [x] Teaser: Talk-Einreichung ()
- [ ] Footer: Kontakt ()
- [x] Über die User Group (#9)
- [ ] Geschichte der User Group (#24)
- [ ] Anleitung zur Talk-Einrichung (#10)
- [x] Kontakt ()
- [ ] Impressum ()
- [ ] Nutzungsbedingungen ()
